;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname q4) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(require rackunit)
(require "extras.rkt")

(provide profit)

;; the current ticket price for the show
(define CURRENT-PRICE 5.0)
;; the current attendees for the show
(define CURRENT-ATTENDEES 120)
;; change in attendees for each 10-cent change in ticket price
(define DELTA-ATTENDEES 15)
;; change in ticket price
(define DELTA-TICKET-PRICE 0.1)

;; attendees : PosReal -> NonNegInt
;; GIVEN: price per ticket in $ rounded to the nearest cent
;; RETURNS: the number of attendees to the show
;; EXAMPLE:
;; (attendees 5.10) = 105
;; (attendees 4.90) = 135
;; STATERGY: combine simpler functions
(define (attendees ticket-price)
  (- CURRENT-ATTENDEES
     (* (- ticket-price CURRENT-PRICE)
        (/ DELTA-ATTENDEES DELTA-TICKET-PRICE))))

(begin-for-test
  (check-equal? (attendees 5.10) 105)
  (check-equal? (attendees 4.90) 135))

;; revenue : PosReal -> PosReal
;; GIVEN: price per ticket in $ rounded to the nearest cent
;; RETURNS: the revenue generated by the sale of tickets
;; EXAMPLE:
;; (revenue 5.20) = 468
;; (revenue 4.80) = 720
;; STATERGY: combine simpler functions
(define (revenue ticket-price)
  (* ticket-price (attendees ticket-price)))

(begin-for-test
  (check-equal? (revenue 5.20) 468)
  (check-equal? (revenue 4.80) 720))

;; the fixed cost for a perfomance to the owner in $
(define FIXED-COST 180)
;; the variable cost per attendee to the owner in $
(define VARIABLE-COST 0.04)

;; cost : PosReal -> PosReal
;; GIVEN: price per ticket in $ rounded to the nearest cent
;; RETURNS: the cost of running the show
;; EXAMPLE:
;; (cost 5.30) = 183
;; (cost 4.70) = 186.6
;; STATERGY: combine simpler functions
(define (cost ticket-price)
  (+ FIXED-COST (* VARIABLE-COST (attendees ticket-price))))

(begin-for-test
  (check-equal? (cost 5.30) 183)
  (check-equal? (cost 4.70) 186.6))

;; profit : PosReal -> PosReal
;; GIVEN: price per ticket in $ rounded to the nearest cent
;; RETURNS: the profit in running the show
;; EXAMPLE:
;; (profit 5.40) = 183
;; (profit 4.60) = 186.6
;; STATERGY: combine simpler functions
(define (profit ticket-price)
  (- (revenue ticket-price) (cost ticket-price)))

(begin-for-test
  (check-equal? (profit 5.40) 141.6)
  (check-equal? (profit 4.60) 640.8))